local formspec_good =
   'formspec_version[3]'..
   'size[10,10]'..
   'bgcolor[;neither]'..
   'image[0,0;10,10;tasks_radio_dish.png]'..
   'hypertext[2,9;6,1;nil;<global halign=center valign=middle><style color=yellow size=30>Signal Strength 97%<style>]'

local function formspec_bad(pos)
   local spos = pos.x ..','.. pos.y ..','.. pos.z
   local formspec =
   'formspec_version[3]'..
   'size[10,10]'..
   'bgcolor[;neither]'..
   'image[0,0;10,10;tasks_radio_dish.png]'..
   'hypertext[2,0;6,2;nil;<global halign=center valign=middle><style color=yellow size=30>No Signal!\nNew Low-noise block required!<style>]'..
   'button_exit[5.125,6.25;3,1;gimme;Grab a request form]'..
   'image[8.875,6.25;1,1;tasks_lnb_line.png]'..
   'list[nodemeta:'..spos..';part;8.875,6.25;1,1;]'..
   'list[current_player;main;.125,7.5;8,2;]'..
   'listring[current_player;main]'..
   'listring[nodemeta:'..spos..';part]'
   return formspec
end

local box = {
   type = 'fixed',
   fixed = {
      {-.5, -.5, -.5, .5, .5, .5}}}

minetest.register_node('tasks:radio_dish_on',{
   description = 'Radio Dish',
   drawtype = 'mesh',
   mesh = 'tasks_radio_dish.obj',
   tiles = {name = 'tasks_radio_dish_on.png'},
   paramtype = 'light',
   paramtype2 = 'facedir',
   selection_box = box,
   collision_box = box,
   groups = {breakable = 1, tasks=1},
   on_construct = function(pos)
      tasks.on_construct(pos, 'Satellite Dish', 'Goofy Umbrella')
   end,
   on_rightclick = function(pos, node, clicker)
      tasks.right_click_on(pos, node, clicker, formspec_good)
   end,
   on_timer = function(pos)
      local node = minetest.get_node(pos)
      local meta = minetest.get_meta(pos)
      local infotext = meta:get_string('info_repair')
      meta:set_string('infotext', infotext)
      minetest.swap_node(pos, {name = 'tasks:radio_dish_off', param2 = node.param2})
   end,
})

minetest.register_node('tasks:radio_dish_off',{
   description = 'Radio Dish',
   drawtype = 'mesh',
   mesh = 'tasks_radio_dish.obj',
   tiles = {name = 'tasks_radio_dish_off.png'},
   paramtype = 'light',
   paramtype2 = 'facedir',
   selection_box = box,
   collision_box = box,
   groups = {breakable = 1, not_in_creative_inventory=1, tasks=1},
   drop = 'tasks:radio_dish_on',
   req_form = 'tasks:lnb_req',
   req_count = 4,
   on_rightclick = function(pos, node, clicker)
      tasks.right_click_off(pos, node, clicker, formspec_bad(pos))
   end,
   allow_metadata_inventory_put = function(pos, listname, index, stack)
      if listname == 'part' then
         if stack:get_name() == 'tasks:lnb' then
            return 1
         else
            return 0
         end
      end
   end,
   on_metadata_inventory_put = function(pos, listname, index, stack, player)
      local name = player:get_player_name()
      local meta = minetest.get_meta(pos)
      local xp = meta:get_int('xp') or 10
      local inv = meta:get_inventory()
      local node = minetest.get_node(pos)
      local timer = minetest.get_node_timer(pos)
      local min = meta:get_int('time_min') or 300
      local max = meta:get_int('time_max') or 600
      local random_number = math.random(min,max)
      local infotext = meta:get_string('info_working')
      inv:set_stack('part', 1, '')
      minetest.swap_node(pos, {name = 'tasks:radio_dish_on', param2 = node.param2})
      minetest.close_formspec(name, 'tasks:part_req_form')
      meta:set_string('infotext', infotext)
      tasks.only_add_xp(xp, name)
      timer:start(random_number)
   end,
   })
