dofile(minetest.get_modpath('lobby')..'/lobby.lua')
dofile(minetest.get_modpath('lobby')..'/buttons.lua')
dofile(minetest.get_modpath('lobby')..'/chat_commands.lua')
dofile(minetest.get_modpath('lobby')..'/chat.lua')
dofile(minetest.get_modpath('lobby')..'/corpse.lua')
dofile(minetest.get_modpath('lobby')..'/emergency_buttons.lua')
dofile(minetest.get_modpath('lobby')..'/formspec.lua')
dofile(minetest.get_modpath('lobby')..'/functions.lua')
dofile(minetest.get_modpath('lobby')..'/player_callbacks.lua')
dofile(minetest.get_modpath('lobby')..'/shop.lua')
dofile(minetest.get_modpath('lobby')..'/stats.lua')
dofile(minetest.get_modpath('lobby')..'/tool.lua')
dofile(minetest.get_modpath('lobby')..'/tdc.lua')

minetest.register_privilege("traitor_dev", {
   description = "Can use /td.",
   give_to_singleplayer = false,
   give_to_admin = true})

minetest.register_privilege("pro_player", {
   description = "Completed the tutorial.",
   give_to_singleplayer = false})

minetest.register_privilege("builder", {
   description = "Can build levels",
   give_to_singleplayer = false})

lobby.load()
minetest.register_on_shutdown(lobby.save)
