local formspec_good =
   'size[6,3]'..
   'textarea[1,1;5,2;;;This plasma accelerator is performing at peak efficiency.]'

local formspec_bad =
   'size[8,6]'..
   'textarea[.5,;5,2;;;Looks like something is broke.\nGet a new part from a storage locker.]' ..
   'button_exit[2.5,1.5;3,1;gimme;Grab a part request form]'..
   'list[current_name;part;6,1;1,1;]'..
   'list[current_player;main;0,3;8,3;]'..
   'listring[current_player;main]'..
   'listring[current_name;part]'

minetest.register_node('tasks:engine_1_on',{
   description = 'Plasma Accelerator',
   drawtype = 'mesh',
   mesh = 'tasks_engine_1.obj',
   tiles = {{name = 'tasks_pedestal.png'},
         {name = 'tasks_engine_1_on.png'},
         {name='tasks_plasma_tube_anim.png',
            animation = {
               type = 'vertical_frames',
               aspect_w = 32,
               aspect_h = 4,
               length = 0.5,},},
         },
   light_source = 13,
   _sound = 'tasks_engine_1_run',
   groups = {breakable = 1, tasks=1, plays_sound=1},
   on_construct = function(pos)
      local meta = minetest.get_meta(pos)
      meta:set_string('formspec', formspec_good)
      meta:set_string('infotext', 'Plasma Accelerator')
      tasks.on_construct(pos)
   end,
   on_rightclick = tasks.right_click,
   on_timer = function(pos)
      local node = minetest.get_node(pos)
      local meta = minetest.get_meta(pos)
      local infotext = meta:get_string('infotext')
      minetest.sound_play('tasks_engine_1_stop', {pos = pos, gain = 1, max_hear_distance = 5})
      meta:set_string('formspec', formspec_bad)
      meta:set_string('infotext', infotext..' (Needs repair!)')
      minetest.after(5, function()
         minetest.swap_node(pos, {name = 'tasks:engine_1_off', param2 = node.param2})
      end)
   end,
})

minetest.register_node('tasks:engine_1_off',{
   description = 'Plasma Accelerator',
   drawtype = 'mesh',
   mesh = 'tasks_engine_1.obj',
   tiles = {{name = 'tasks_pedestal.png'},
         {name = 'tasks_engine_1_off.png'},
         {name='tasks_plasma_tube.png'},
         },
   light_source = 2,
   groups = {breakable = 1, not_in_creative_inventory=1, tasks=1},
   drop = 'tasks:engine_1_on',
   on_receive_fields = function(pos, formname, fields, sender)
      if fields ['gimme'] then
         local player_inv = sender:get_inventory()
         if not player_inv:contains_item('main', {name='tasks:plasma_core_req', count = 4}) then
            player_inv:add_item('main', 'tasks:plasma_core_req')
         else
            minetest.chat_send_player(sender:get_player_name(), 'You have too many of these already.')
         end
      end
   end,
   allow_metadata_inventory_put = function(pos, listname, index, stack)
      if listname == 'part' then
         if stack:get_name() == 'tasks:plasma_core' then
            return 1
         else
            return 0
         end
      end
   end,
   on_metadata_inventory_put = function(pos, listname, index, stack, player)
      local name = player:get_player_name()
      local meta = minetest.get_meta(pos)
      local xp = meta:get_int('xp') or 1
      local inv = meta:get_inventory()
      local node = minetest.get_node(pos)
      local timer = minetest.get_node_timer(pos)
      local min = meta:get_int('time_min') or 30
      local max = meta:get_int('time_max') or 60
      local random_number = math.random(min,max)
      local infotext = string.sub(meta:get_string('infotext'), 1, -17)
      inv:set_stack('part', 1, '')
      minetest.sound_play('tasks_engine_1_start', {pos = pos, gain = 1, max_hear_distance = 10})
      minetest.swap_node(pos, {name = 'tasks:engine_1_on', param2 = node.param2})
      meta:set_string('formspec', formspec_good)
      meta:set_string('infotext', infotext)
      tasks.only_add_xp(xp, name)
      timer:start(random_number)
   end,
})
